### PR TITLE
Bug when executing external process from Java application

### PR DESCRIPTION
**Pull request by sbamamoto**
These commits fixing two bugs. 
The first bug was impossibility to run an external process from the Java application in the .dmg file. This was caused by a missing executable flag for a helper application named jspwanhelper.
The other fixes the JRE detection which was buggy. This leads to duplicate JRE files in the .dmg file.

### CODE REVIEW

**Comment by federkasten** [comment]
Thanks. I will review soon : )

**Comment by sbamamoto** [comment]
Sorry, but reworked it again. It is now faster, safer and more elegant ;)

**Comment by azhemoytuk** [comment]
@federkasten do you think this pull request can be merged as well and new version released with all the recent changes?

**Comment by federkasten** [comment]
@azhemoytuk Sorry for late. I will review and release in this week.

**Pull request merged**
