### PR TITLE
JRE Embedding Feature added

### PR DESCRIPTION
**Pull request by sbamamoto**
Hi,

I added the embed JRE feature. I tested it with maven on MacOS Yosemite.
My changes added a new configuration property called jrePath where a path to the root of a jre or idk can be set as source. During the build the the idk/jre is copied to the app bundle and execute permissions are set for the executables.

I took a look at the code of the JavaAppLauncher and registered that there is a hardcoded path information that forces the usage of a JDKs only. I added and tested a workaround to make it possible to use both JDK and JRE.

If you have any questions let me know.

### CODE REVIEW

**Comment by federkasten** [comment]
Merged. Thank you ;)

**Comment by jdiligence** [comment]
Great news. 

I also need to include other executables as the java app needs to call them. Is this possible currently? I have been using jarbundler for this reason so far but would switch to appbundler if it can do that.

**Comment by federkasten** [comment]
That is currently impossible. Sorry.

Maybe you can do it using `additionalResources` or `additionalBundledClasspathResources` configurations, but these functions contains a bug (c.f #15).

**Comment by jdiligence** [comment]
I can include extra resources but I can't see how to change their permissions to executable. Unfortunately my java app is largely a UI front end to other binaries.

**Pull request merged**
